spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/messages
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: ${RABBIT_PASS:guest}
    username: ${RABBIT_USER:guest}
    port: ${RABBIT_PORT:5672}
  rabbit:
    queue:
      status: ${STATUS_QUEUE:status}

clients:
  client-ms: ${CLIENT_MS:localhost:8080}
service:
  channel-name: ${CHANNEL_NAME:message}

rabbit:
  queue:
    entries: ${SEND_PROVISION_QUEUE:entries}
server:
  port: 8082